#!/usr/bin/python3

import sys
import time

def factorize_function(value):
    for num in range(2, int(value/2) + 1):
        if value % num == 0:
            return num, int(value / num)
    return None

if __name__ == '__main__':
    """
        this program runs the sript directly as the main file
        or if it is being imported into another script
    """
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    my_file = sys.argv[1]
    try:
        with open(my_file, 'r') as file:
            rows = file.readlines()
    except FileNotFoundError:
        print("No file found")
        exit()

    begining = time.time()
    for i in rows:
        """
            loops and checks for natural number
            then prints factorized numbers
        """
        number = int(i.strip())
        f_actor = factorize_function(number)
        if f_actor:
            print(f"{number}={f_actor[0]}*{f_actor[1]}")

        if time.time() - begining > 5:
            """
                program exit if function runs for more than 5 secs
            """
            print("Session timed out")
            exit()
