#!/usr/bin/env python3

import sys
import subprocess

def prime_numbers(*value):
    if len(value) != 3:
        variable_1 = 1
        for num, i in enumerate(value):
            if num > 1:
                variable_1 *= i
        variable_2 = value[1]
    else:
        variable_2 = value[1]
        variable_1 = value[2]

    number = value[0].replace(':', '=')
    if variable_1 > variable_2:
        variable_2, variable_1 = variable_1, variable_2

    print("%s%s*%s" % (number, variable_1, variable_2))

if len(sys.argv) != 2:
    print("Usage: rsa <file>")
    sys.exit(1)

with open(sys.argv[1], 'r') as f:
    for line in f:
        number_1 = line.strip()
        factor_output = subprocess.check_output(['factor', number_1])
        factors = list(map(int, factor_output.decode().split()[1:]))
        prime_numbers(*([line.strip()] + factors))

