#!/usr/bin/env python3

import sys
import subprocess

def prime_numbers(number, factor_1, factor_2):
    if factor_1 > factor_2:
        factor_1, factor_2 = factor_2, factor_1
    print("%s=%s*%s" % (number, factor_1, factor_2))

if len(sys.argv) != 2:
    print("Usage: rsa <file>")
    sys.exit(1)

with open(sys.argv[1], 'r') as f:
    for line in f:
        number = line.strip()
        factor_output = subprocess.check_output(['factor', number])
        factors = list(map(int, factor_output.decode().split()[1:]))
        prime_numbers(number, *factors)

